name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install packages
        run: npm install
      - name: Typecheck
        run: npm run typecheck --workspaces
      - name: Build frontend
        run: npm run build
